#!/bin/sh

set -eu

jobid=20220430-182343-ce41
subjob=$1
num_subjobs=31

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000210-mriqc/.reproman/jobs/local/20220430-182343-ce41
rootdir=/home1/03201/jbwexler/.reproman/run-root
workdir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000210-mriqc

_reproman_cmd_idx=$(($subjob + 1))
export _reproman_cmd_idx

echo "submitted" >"$metadir/status.$subjob"
echo "[ReproMan] pre-command..."

cd "$workdir"

get_command () {
    perl -n0e \
         '$idx=$ENV{_reproman_cmd_idx}; print "$_" if $. == $idx;' \
         "$metadir/command-array"
}

cmd=$(get_command)
if test -z "$cmd"
then
    echo "[ReproMan] failed getting command at position $_reproman_cmd_idx" >&2
    echo "pre-command failure" >"$metadir/status.$subjob"
    exit 1
fi

echo "running" >"$metadir/status.$subjob"
echo "[ReproMan] executing command $cmd"
echo "[ReproMan] ... within $PWD"
/bin/sh -c "$cmd" && \
    echo "succeeded" >"$metadir/status.$subjob" || \
    (echo "failed: $?" >"$metadir/status.$subjob";
     mkdir -p "$metadir/failed" && touch "$metadir/failed/$subjob")

nstatus () {
    grep -E '^(succeed|fail)' "$metadir"/status.* | wc -l
}

if test $(nstatus) -eq 1; then

	echo "[ReproMan] waiting for threshold of jobs to complete before continuing..."

	killjob_factors=.85,.25
	threshold_factor=$(echo "$killjob_factors" | awk -F, '{ print $1 }')
	add_time_factor=$(echo "$killjob_factors"| awk -F, '{ print $2 }')
	majority_num=$(echo "$num_subjobs * $threshold_factor" | bc -l | xargs printf "%.0f\n")

	echo "threshold_factor = $threshold_factor"
	echo "add_time_factor = $add_time_factor"
	echo "majority_num = $majority_num"

	while test $(nstatus) -lt "$majority_num"; do
	    sleep 1
	done
	
	runtime_stamp=$(squeue --job "$SLURM_JOB_ID" | tail -n 1 | awk '{ print $6 }')
	runtime_seconds=$(echo "$runtime_stamp" | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
	if [[ "$runtime_stamp" == *"1-"* ]]; then
		runtime_seconds=$((runtime_seconds+86400))
	fi
	add_time_seconds=$(echo "$runtime_seconds * $add_time_factor" | bc -l | xargs printf "%.0f\n")
	echo "runtime_stamp = $runtime_stamp"
	echo "runtime_seconds = $runtime_seconds"
	echo "add_time_seconds = $add_time_seconds"
	echo "[ReproMan] waiting for all jobs to complete before running post-command..."
	count=0
	while test $(nstatus) -lt "$num_subjobs" && test "$count" -lt "$add_time_seconds"; do
	    sleep 10
		count=$((count+10))
	done

	echo "[ReproMan] post-command..."

		
	mkdir -p "$rootdir/completed/"
	touch "$rootdir/completed/$jobid"

	if test $(nstatus) -lt "$num_subjobs"; then 
		scancel "$SLURM_JOB_ID"
	fi
fi